version: "3"
services:
  frpc:
    build: .
  nginx:
    image: nginx
    hostname: nginx
    ports:
      - 1337:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/app/static/index.html
